NAME	= megaphone
FLAGS	= -Wall -Wextra -Werror -std=c++98
SRCS	= megaphone.cpp
OBJS	= ${SRCS:.cpp=.o}

all: ${NAME}

${NAME}: ${OBJS}
	c++ ${FLAGS} -o ${NAME} ${OBJS}

%.o: %.cpp
	c++ ${FLAGS} -c $< -o $@

clean:
	rm -f ${OBJS}

fclean: clean
	rm -f ${NAME}

re: fclean all

.PHONY: all clean fclean re
